[build]
target = "./triples/ia32legacy.json"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]

[target.ia32legacy]
rustflags = [
    "-C", "relocation-model=pic",
    "-C", "code-model=medium",
    "-C", "link-arg=--shared",
    "-C", "link-arg=--exclude-libs=ALL",
    "-C", "link-arg=--version-script=./triples/ia32legacy.lds",
    "-C", "link-arg=--gc-sections",
    "-C", "link-arg=--as-needed",
    "-C", "link-arg=--icf=all",
    "-C", "link-arg=--strip-all",
]
