[build]
target = "./triples/ia32legacy.json"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]

[target.ia32legacy]
rustflags = [
    "-C", "linker=rust-lld",
    "-C", "link-arg=-T./triples/ia32legacy.lds",
]

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.release]
opt-level = 3
debug = false
panic = "abort"
